# Path A2G CU — F1 northbound to ATG DUs (ground ATG BS).
# SIB19 not used (TR 38.876 ground BS <-> aircraft UE).
# SPDX-License-Identifier: LicenseRef-CSSL-1.0

Active_gNBs = ( "cu-a2g");
Asn1_verbosity = "none";

gNBs =
(
 {
    gNB_ID = 0xe00;
    gNB_name  =  "cu-a2g";

    tracking_area_code  =  1;
    plmn_list = ({ mcc = 001; mnc = 01; mnc_length = 2; snssaiList = ({ sst = 1; }) });

    nr_cellid = 12345678L;

    # Terrestrial CU SIB2 only per TR 38.876 (no SIB19)
    cu_sibs = [2];

    tr_s_preference = "f1";

    local_s_address     = "127.0.0.3";
    remote_s_address    = "0.0.0.0";
    local_s_portd       = 2153;
    remote_s_portd      = 2153;

    SCTP :
    {
        SCTP_INSTREAMS  = 2;
        SCTP_OUTSTREAMS = 2;
    };

    amf_ip_address = ({ ipv4 = "192.168.70.132"; });

    NETWORK_INTERFACES :
    {
        GNB_IPV4_ADDRESS_FOR_NG_AMF              = "192.168.70.129/26";
        GNB_IPV4_ADDRESS_FOR_NGU                 = "192.168.70.129/26";
        GNB_PORT_FOR_S1U                         = 2152;
    };
  }
);

security = {
  ciphering_algorithms = ( "nea0" );
  integrity_algorithms = ( "nia2", "nia0" );
  drb_ciphering = "yes";
  drb_integrity = "no";
};

log_config : {
  global_log_level = "info";
  pdcp_log_level = "info";
  rrc_log_level = "info";
  f1ap_log_level = "info";
  ngap_log_level = "info";
};
