# Path A2G nrUE ue1 — default single-UE identity (IMSI …001).
# MULTI_UE=1: RFsim SERVER (Path B). MULTI_UE>=2: RFsim CLIENT to DU:4043.
# SPDX-License-Identifier: LicenseRef-CSSL-1.0

uicc0 = {
  imsi = "001010000000001";
  key = "fec86ba6eb707ed08905757b1bb44b8f";
  opc= "C42449363BBAD02B66D16BC975D77CC1";
  pdu_sessions = ({ dnn = "oai"; nssai_sst = 1; });
};

position0 = {
    x = 0.0;
    y = 0.0;
    z = 6387900.0;  # ~10 km AGL (TR 38.876 lab convention)
};

rfsimulator = (
  {
    serveraddr = "server";
    serverport = 4043;
    options = ();
  }
);
