# Path A2G nrUE ue3 — RFsim CLIENT to DU server :4043 (MULTI_UE>=3).
# SPDX-License-Identifier: LicenseRef-CSSL-1.0

uicc0 = {
  imsi = "001010000000003";
  key = "fec86ba6eb707ed08905757b1bb44b8f";
  opc= "C42449363BBAD02B66D16BC975D77CC1";
  pdu_sessions = ({ dnn = "oai"; nssai_sst = 1; });
};

position0 = {
    x = -400.0;
    y = 200.0;
    z = 6385900.0;  # ~8 km AGL
};

rfsimulator = (
  {
    serveraddr = "127.0.0.1";
    serverport = 4043;
    options = ();
  }
);
